// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7MQoUsnCPQnvm364Vz4pvluH1dwwPXJs',
    appId: '1:10175789217:web:404c41609810a7641858e0',
    messagingSenderId: '10175789217',
    projectId: 'conectados-761fa',
    authDomain: 'conectados-761fa.firebaseapp.com',
    storageBucket: 'conectados-761fa.appspot.com',
    measurementId: 'G-QMFWE0N9HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYLDRxj6vCMiVXlQ564inCwCLK-cgle5g',
    appId: '1:10175789217:android:232121ee3be4acbe1858e0',
    messagingSenderId: '10175789217',
    projectId: 'conectados-761fa',
    storageBucket: 'conectados-761fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrS1vBpPXiK4QzqF7GGjYKCxx0mb3Nuow',
    appId: '1:10175789217:ios:e0836702bb48c1aa1858e0',
    messagingSenderId: '10175789217',
    projectId: 'conectados-761fa',
    storageBucket: 'conectados-761fa.appspot.com',
    iosClientId: '10175789217-d173oaulji8qkfajslc39gfg1j36bdnl.apps.googleusercontent.com',
    iosBundleId: 'no',
  );
}
